# ─────────────────────────────────────────────────────────────────────────
# mostly-noise site configuration
# ─────────────────────────────────────────────────────────────────────────

title:       "mostly-noise"
description: "Digital garden of sorts. Still exploring!"
url:         "https://cisconaut.github.io"   # your root URL
baseurl:     "/mostly-noise"                 # project site subpath
timezone:    "Europe/London"
encoding:    "utf-8"

# ─────────────────────────────────────────────────────────────────────────
# Theme preferences
# ─────────────────────────────────────────────────────────────────────────
heading:     "mostly-noise"                 # site header
content:     "Digital garden powered by Jekyll & Obsidian"  
copyright:
  year:      "© 2025"
  msg:       "Contents under CC-BY-NC"

preferences:
  search:
    enabled: true
  wiki_style_link: 
    enabled: true
  pagepreview: 
    enabled: true
  backlinks:
    enabled: true
  homepage: 
    enabled: true

# ─────────────────────────────────────────────────────────────────────────
# Plugins & Collections
# ─────────────────────────────────────────────────────────────────────────
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-tidy

collections:
  notes:
    output:    true
    permalink: /note/:title

# ─────────────────────────────────────────────────────────────────────────
# Markdown & build settings
# ─────────────────────────────────────────────────────────────────────────
markdown: kramdown
kramdown:
  input:              GFM
  hard_wrap:          false
  math_engine:        katex
  smart_quotes:       ["apos", "apos", "quot", "quot"]
  syntax_highlighter: rouge

sass:
  style: compressed

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout:      Post
      permalink:   /post/:title
      content-type: post
  - scope:
      path: ""
      type: notes
    values:
      layout:       Post
      content-type: notes

# ─────────────────────────────────────────────────────────────────────────
# Exclude private/template notes
# ─────────────────────────────────────────────────────────────────────────
exclude:
  - _notes/000\ Inbox
  - _notes/200\ Private
  - _notes/300\ Templates




